---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ricshoec/public_html/
    - /bin/mkdir -p /home/ricshoec/public_html/
    - if [ "${PWD%/}" != "/home/ricshoec/public_html" ]; then /bin/cp -R * /home/ricshoec/public_html/; fi
    - /bin/mkdir -p /home/ricshoec/public_html/tmp
    - /bin/touch /home/ricshoec/public_html/tmp/restart.txt
    - cd /home/ricshoec/public_html/ && npm install
    - cd /home/ricshoec/public_html/ && npm run build
    - /bin/mkdir -p /home/ricshoec/public_html/public
    - /bin/cp -R /home/ricshoec/public_html/dist/* /home/ricshoec/public_html/public/
